# Generated by Django 3.2.7 on 2021-10-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
