# Generated by Django 3.2.7 on 2021-10-05 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbook', '0005_auto_20211004_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['create_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages_by_chat', to='fbook.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_by_user', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
