# Generated by Django 3.2.7 on 2021-10-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbook', '0006_auto_20211005_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
